spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jpa:
  database: mysql
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      format_sql: true

mybatis:
  mybatis.type-aliases-package: com.todook.crocodile # xml 파일 result type에 패키지명을 생략할 수 있도록 alias 설정
  mapper-locations: mybatis/**/*.xml # mapper 파일 경로 설정
  configuration.map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정

crocodile:
  allowed-referers:
    - http://localhost:8080
    - http://localhost:3000
    - https://todook-server-production.up.railway.app

logging:
  level:
    jdbc:
      sqlonly: off # SQL 문을 보여준다
      sqltiming: debug # SQL 문과 이 SQL 문을 수행하는 시간을 같이 보여준다
      resultsettable: off # ResultSet 을 제외한 모든 JDBC 호출 정보를 로그로 보여준다.
      audit: off
      resultset: off # SQL 의 결과로 조회된 데이터를 table 형태로 로그를 보여준다.
      connection: off # DB 연결, 연결 해제와 관련된 로그를 보여준다.

oauth2:
  kakao:
    client-id: 2d03df3830cb6e458063fc862acf041b
    client-secret: 929XNpfIWB7kHfIXKmZaGi10hkCSjQMt
    redirect-uri: "https://bobby-djk.herokuapp.com/api/oauth2/callback/kakao"
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: 4phPhh0_MG0qX51vklfy
    client-secret: Q4A3CPGjq1
    redirect-uri: "https://bobby-djk.herokuapp.com/api/oauth2/callback/naver"
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me

# local
---
spring:
  config:
    activate:
      on-profile: local # 스프링부트를 띄울때 profile이 local 이면 아래 설정을 따르도록 합니다.
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/board?characterEncoding=utf8
    username: root
    password: 1234

oauth2:
  kakao:
    redirect-uri: "http://localhost:8080/api/oauth2/callback/kakao"
  naver:
    redirect-uri: "http://localhost:8080/api/oauth2/callback/naver"