spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

crocodile:
  allowed-referers:
    - http://localhost:8080
    - http://localhost:3000
    - https://todook-server-production.up.railway.app
